Request to merge feature desktop version
Kingstalux/Project_Portfolio_Mobile_Skeletun pull request #4
Opened 2021-08-20 17:52 UTC by Kingstalux

Created UIs adaptable to different screen sizes using media queries.
 I applied media queries to make sure that my website displays correctly on mobile, iPad, iPad pro, and desktop screens.

2021-08-20 19:15 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @Kingstalux, You did a great job so far 👏🏼 👏🏼 

- Commit messages are descriptive.
- Project is professional.
- Pull request is professional.

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [x] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a screenshot to your Readme. To give people an idea how the project looks like.
- Deploying the webpage [on Github pages](https://anilemrah.medium.com/how-to-publish-your-html-with-github-pages-8f3f854e7d4)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-20 19:15 UTC, safafa commented on README.md
> +
- [x] [OPTIONAL] I think it's better to remove this link or replace it with a live demo link of github pages.

2021-08-20 19:15 UTC, safafa commented on index.html
> +      <img src="img.png" alt="picture">
- [x] The image is not showing as it should. I think because you mistyped the src. it should be `src="Img.png"` Kindly fix it.

2021-08-20 19:15 UTC, safafa commented on index.html
> +        <button type="button" class="button1">See Project</button>
- [x] Your project looks a bit different from the original design. As you can see here.
![image](https://user-images.githubusercontent.com/43698511/130280138-93f5b141-ecb8-418e-9deb-dfe712c58673.png)
In the original design, the featured project and the other projects are aligned. Yours is bit moving to the right; Kindly fix this issue.
![image](https://user-images.githubusercontent.com/43698511/130280262-8f69bedd-bed1-4606-b2a8-44ba285e87be.png)

- [x] As you can see in the image. The featured project image is taking like 60% and the description takes the remaining 40%; Kindly make this change.
 
![image](https://user-images.githubusercontent.com/43698511/130280862-2e6ea968-4ed7-4000-b650-ac17167fdd57.png)


- [x] The font size of the project title is a bit bigger in the original design. And the font family is also different. Kindly make this change.

2021-08-20 19:15 UTC, safafa commented on index.html
> +        </div>
- [ ] For this part, not all the projects are showing. Kindly fix the issue.
![image](https://user-images.githubusercontent.com/43698511/130281383-37af904b-258f-41dd-9e72-d2e65ba91de6.png)

- [ ] In the original design. All the featured projects have the description on top of their image with a dark opacity with white color text. When the project is hovered on with the mouse the description and dark opacity disappear and a See Project button appears. Kindly fix the issue.
![image](https://user-images.githubusercontent.com/43698511/130281979-44812061-cd82-4f43-8961-99df40e5a6dd.png)

2021-08-21 10:14 UTC, Kingstalux commented on README.md
> +
ok thanks

2021-08-21 11:07 UTC, SajjadAhmad14 commented on index.html
>    <section class="works">
[ OPTIONAL ]Please align `Multi post stories` with the project after it horizontally. Please see below screenshot for reference.
![works](https://user-images.githubusercontent.com/35504149/130319849-b4146274-766e-44f8-ae9e-962b8793c18c.png)

2021-08-21 11:09 UTC, SajjadAhmad14 commented on index.html
>  <body>
[ OPTIONAL ] Please create a directory named images and put all the image resources in it. It looks managed and nice when different directories are utilized.

2021-08-21 11:09 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Kingsely Ngu, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL
- [x] Please see inline comments.
## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-21 11:11 UTC, merged